---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kaoshi
  name: front-management
  labels:
    app: front-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-management
  template:
    metadata:
      labels:
        app: front-management
    spec:
      containers:
      - name: front-management
        image: registry.cn-hangzhou.aliyuncs.com/xiaodong_li/exam-management
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: kaoshi
  name: front-management-svc
spec:
  ports:
   - port: 80
     targetPort: 80
  selector:
   app: front-management
